apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/cadent-io/flow-sandbox:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/cadent-io/flow-sandbox:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: flow-sandbox
        chartPath: charts/flow-sandbox
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/cadent-io/flow-sandbox"
          image.tag: "{{.DIGEST_HEX}}"
